apiVersion: v1
kind: Service
metadata:
  name: "${ACCOUNT_GRAPH_SERVICE_NAME@microservice-account-config}"
  namespace: "${NAMESPACE@microservice-config}"
  labels:
    moduleid: microservice-auth-realm
    version: 1.70.4-master
spec:
  type: ClusterIP
  selector:
    app: "${ACCOUNT_GRAPH_DEPLOYMENT_NAME}"
  ports:
    - name: port
      port: "${ACCOUNT_GRAPH_INTERNAL_PORT@microservice-account-config}"
