apiVersion: v1
kind: Service
metadata:
  name: "${CACHE_SERVICE_NAME@microservice-auth-config}"
  namespace: "${NAMESPACE@microservice-config}"
  labels:
    moduleid: microservice-auth-realm
    version: 1.70.3-master
spec:
  type: ClusterIP
  ports:
    - port: "${CACHE_INTERNAL_PORT@microservice-auth-config}"
      targetPort: "${CACHE_INTERNAL_PORT@microservice-auth-config}"
  selector:
    app: "${CACHE_STATEFUL_NAME}"
