apiVersion: v1
kind: Service
metadata:
  name: "${DATA_SERVICE_NAME@microservice-auth-config}"
  namespace: "${NAMESPACE@microservice-config}"
  labels:
    moduleid: microservice-auth-data
    version: 1.70.4-master
spec:
  type: ClusterIP
  ports:
    - port: "${DATA_INTERNAL_PORT@microservice-auth-config}"
      targetPort: "${DATA_INTERNAL_PORT@microservice-auth-config}"
  selector:
    app: "${DATA_STATEFUL_NAME}"
