apiVersion: v1
kind: Service
metadata:
  name: "${GRAPH_SERVICE_NAME@microservice-auth-config}"
  namespace: "${NAMESPACE@microservice-config}"
  labels:
    moduleid: microservice-auth-realm
    version: 1.70.8-master
spec:
  type: NodePort
  selector:
    app: "${GRAPH_DEPLOYMENT_NAME}"
  ports:
    - name: port
      port: "${GRAPH_INTERNAL_PORT@microservice-auth-config}"
