apiVersion: v1
kind: Service
metadata:
  name: "${QUEUE_SERVICE_NAME@microservice-auth-config}"
  namespace: "${NAMESPACE@linker-config}"
  labels:
    moduleid: linker-auth-realm
    version: 1.70.3-master
spec:
  type: ClusterIP
  ports:
    - name: "queue"
      port: "${QUEUE_INTERNAL_PORT@microservice-auth-config}"
      targetPort: "${QUEUE_INTERNAL_PORT@microservice-auth-config}"
    - name: "manager"
      port: "${QUEUE_MGR_INTERNAL_PORT@microservice-auth-config}"
      targetPort: "${QUEUE_MGR_INTERNAL_PORT@microservice-auth-config}"
  selector:
    app: "${QUEUE_STATEFUL_NAME}"
