apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "${QUEUE_VOLUME_NAME}"
  namespace: ${NAMESPACE@linker-config}
  labels:
    service: "${QUEUE_SERVICE_NAME@microservice-auth-config}"
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-storage
  hostPath:
    path: /home/docker/production/${HOST@linker-config}/volumes/${QUEUE_VOLUME_NAME}
