apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${GRAPH_DEPLOYMENT_NAME}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${GRAPH_DEPLOYMENT_NAME}'
    moduleid: microservice-auth-realm
    version: 1.70.0-data-reconnect-initial-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${GRAPH_DEPLOYMENT_NAME}'
  template:
    metadata:
      labels:
        app: '${GRAPH_DEPLOYMENT_NAME}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-auth-graph-container:1.70.7-master'
          env:
            -
              name: AUTH_ROUTE_GRAPH
              value: '${GRAPH_BASE_ROUTE@microservice-auth-config}'
            -
              name: AUTH_INTERNAL_PORT_GRAPH
              value: '${GRAPH_INTERNAL_PORT@microservice-auth-config}'
            -
              name: AUTH_CACHE_INTERNAL_HOST
              value: '${CACHE_INTERNAL_HOST@microservice-auth-config}'
            -
              name: AUTH_CACHE_INTERNAL_PORT
              value: '${CACHE_INTERNAL_PORT@microservice-auth-config}'
            -
              name: AUTH_CACHE_SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '${CACHE_SECRET_NAME}'
                  key: password
            -
              name: ACCOUNT_INTERNAL_URL_GRAPH
              value: '${ACCOUNT_GRAPH_INTERNAL_URL@microservice-auth-config}'
          ports:
            -
              containerPort: '${GRAPH_INTERNAL_PORT@microservice-auth-config}'
